source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.0'

gem 'rails', '~> 7.0.0'
gem 'mysql2', '~> 0.5'
gem 'puma', '~> 5.0'
gem 'bootsnap', '>= 1.4.4', require: false

# CORS handling
gem 'rack-cors'

# Authentication
gem 'devise'
gem 'devise-jwt'

# Image upload
gem 'image_processing', '~> 1.2'

# API serialization
gem 'active_model_serializers'

# Pagination
gem 'kaminari'

# Geocoding for aquarium locations
gem 'geocoder'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'spring'
end